development:
  adapter: mysql2
  encoding: utf8
  database: db_development
  pool: 5
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  database: db_test
  pool: 5
  username: root
  password:
  timeout: 5000
  host: '127.0.0.1'

production:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
